tunnel: 52a49a9e-d70b-483b-961c-b1e93a3f97fa
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: dockerstacks3proxy.dpdns.org
    service: http://caddy:80
  - hostname: main.dockerstacks3proxy.dpdns.org
    service: http://caddy:80
  - hostname: ttyd.dockerstacks3proxy.dpdns.org
    service: http://caddy:80
  - hostname: dozzle.dockerstacks3proxy.dpdns.org
    service: http://caddy:80
  - hostname: files.dockerstacks3proxy.dpdns.org
    service: http://caddy:80
  - service: http_status:404
